src/Ninja/G1CP/Content/Fixes/Session/fix059_FixEquipBestWeapons.d, src/Ninja/G1CP/Content/NinjaInit.d
These changes should fix the bug #59. Quoting #59 for a minor issue:
> A few words about the fix. It will prevent NPCs from equipping a weapon when they already have one of the type equipped. That means in particular:
> 
> 1. If an NPC is created with a melee weapon, they will stick to this weapon for the entire game, unless explicitly exchanged through the scripts.
> 1. If an NPC is created *without* a ranged weapon, they will equip a ranged weapon should they ever acquire one (e.g. through trading with the player).
> 
> In short: An NPC **willl auto-equip** a ranged *and* a melee weapon if available - but **only the first time**.
> 
> So, you could argue the fix only works to a certain extend. In most cases, the first sold ranged weapon will be "lost" for most traders.
_Originally …
=> Fix #59 weapon auto-equipping

src/Ninja/G1CP/Content/Fixes/Session/fix015_HoratioStrength.d, src/Ninja/G1CP/Content/NinjaInit.d, src/Ninja/G1CP/Content/Tests/test015.d, src/Ninja/G1CP/Content_G1.src
This fix wraps around the dialog of Horatio to revert the strength should it have decreased. As a bonus, the `PrintScreen` call is intercepted to replace the on-screen information accordingly.
You may run a test with `test 15` from the in-game console.
=> #15 fix strengh decrease in Horatio's dialog

src/Ninja/G1CP/Content/Fixes/Session/fix003_RegainDroppedWeapon.d, src/Ninja/G1CP/Content/Misc/Npc_CanSeeVob.d, src/Ninja/G1CP/Content/NinjaInit.d, src/Ninja/G1CP/Content/Tests/test003.d, src/Ninja/G1CP/Content_G1.src
This fix is a little more elaborate to ensure that the underlying function `B_RegainDroppedWeapon` is still called instead of fully replaced. This is to ensure that any new code added to the function is still being called and the patch does not interfere.
The following issues are addressed:
- The NPC now correctly picks up the detected item, even if they have to turn around
- The NPC now only picks up a weapon if they don't already have one of the type equipped
- The NPC now no longer equips the best weapon, but the one that was picked up (complementing #59)
The test of the fix requires manual confirmation: Run `test 3` from the console and watch an NPC getting inserted, equipped with a bow, and some loose weapons on the ground. Regardless of where the NPC is facing, it should turn to the …
=> #3 correctly pick up weapons after fight

src/Ninja/G1CP/Content/Fixes/Session/fix017_JackalProtectionMoney.d, src/Ninja/G1CP/Content/NinjaInit.d, src/Ninja/G1CP/Content/Tests/test017.d, src/Ninja/G1CP/Content_G1.src
There is simple a new condition added (before the remaining dialog conditions are checked) whether the hero is assigned to a guild.
You may run a test with `test 17`
=> #17 add new condition to jackal's dialog

src/Ninja/G1CP/Content/Fixes/Session/fix018_BloodwynProtectionMoney.d, src/Ninja/G1CP/Content/NinjaInit.d, src/Ninja/G1CP/Content/Tests/test018.d, src/Ninja/G1CP/Content_G1.src
Like #65 this PR checks whether the player has a guild or not.
The fix can be tested with `test 18`.
Closes #18.
=> #18: Add new condition to Bloodwyn's dialog

src/Ninja/G1CP/Content/Fixes/Session/fix007_PracticeSwordWithWeapon.d, src/Ninja/G1CP/Content/NinjaInit.d, src/Ninja/G1CP/Content/Tests/test007.d, src/Ninja/G1CP/Content_G1.src
This fix is a bit more elaborate than proposed [here](https://github.com/AmProsius/gothic-1-community-patch/issues/7#issuecomment-757119039).
There are different scenarios:
1. The NPC has a melee weapon equipped but not drawn. -> Draw weapon
2. The NPC doesn't have a weapon equipped. -> Search if a weapon is available, eqiup and draw it
3. The NPC doesn't have a weapon in their inventory. -> Switch to `ZS_StandAround`
4. The NPC doesn't have a weapon and `ZS_StandAround` does not exist (for some reason). -> Do sword practice without a weapon and make a fool out of yourself.
=> #7 fix sword practice

src/Ninja/G1CP/Content/Fixes/Session/fix001_FixNpcSleep.d, src/Ninja/G1CP/Content/NinjaInit.d, src/Ninja/G1CP/Content/Tests/test001.d, src/Ninja/G1CP/Content/misc.d, src/Ninja/G1CP/Content_G1.src
This PR is not ready for merging yet. The issue below should be addressed first.
Are you sure this works as expected? A check against `Npc_GetBodyState` rarely renders true, because the body state is a bitfield, a combination of multiple active body states. That's why there is the function `C_BodyStateContains`. Is there a particular reason why you used `Npc_GetBodyState`?
_Originally posted by @szapp in https://github.com/AmProsius/gothic-1-community-patch/issues/1#issuecomment-761538175_
To test this fix, manual confirmation is required: When running `test 1` from the console, the hero is teleported to a hut at night. The user can confirm if the NPC inside remains asleep.
=> #1 make NPCs sleep properly

src/Ninja/G1CP/Content/Fixes/Session/fix002_FixDoor.d, src/Ninja/G1CP/Content/NinjaInit.d, src/Ninja/G1CP/Content/Tests/test002.d, src/Ninja/G1CP/Content_G1.src
NPCs now use doors properly.
This PR should be ready to merge. An interesting thing to check would be, whether it also works when using with mods that already have fixed the issue.
The test involves manual confirmation with `test 2`.
=> #2 NPC use doors properly

src/Ninja/G1CP/Content/Fixes/Session/fix009_FixFlee.d, src/Ninja/G1CP/Content/NinjaInit.d, src/Ninja/G1CP/Content/Tests/test009.d, src/Ninja/G1CP/Content_G1.src
This PR should be ready.
Testing this fix is a bit tricky, because the NPC has to be visible all times while fleeing from the player. The rest requires to position the hero in a location surrounded by as many NPCs as possible to increase the chances of observing (not observing) the freeze. It's best to run the test first without and then with the fix, to remember where freezes do happen without the fix. To do so remove the fix here: 
https://github.com/AmProsius/gothic-1-community-patch/blob/ca8adc9d50a1c8e48340cbfd70702ccdddde4f72/src/Ninja/G1CP/Content/NinjaInit.d#L20
Run the test with `test 9`.
=> #9: Remove freeze from fleeing

src/Ninja/G1CP/Content/Fixes/Session/fix010_FollowWalkMode.d, src/Ninja/G1CP/Content/NinjaInit.d, src/Ninja/G1CP/Content/Tests/test010.d, src/Ninja/G1CP/Content/misc.d, src/Ninja/G1CP/Content_G1.src
The NPC will now adjust their walking speed (walking vs. running) according to the player.
1. Player runs: NPC runs.
2. Player walks: NPC walks - as soon as close enough to the player
3. Player runs again: NPC starts running immediately - only works if there is line of sight!
Test: Manual confirmation required. Run `test 10`.
Closes #10.
=> #10: Adjust walk mode in follow state

src/Ninja/G1CP/Content/Fixes/Session/fix024_CorKalomWrongQuest.d, src/Ninja/G1CP/Content/NinjaInit.d, src/Ninja/G1CP/Content/Tests/test024.d, src/Ninja/G1CP/Content_G1.src
Though this test is automatic, afterwards the mission's are closed. The game should be saved before and loaded after.
Run the test with `test 24`.
Closes #24.
=> #24: Cor Kalom closes correct quest

src/Ninja/G1CP/Content/Fixes/Session/fix031_WolfPlateDialog.d, src/Ninja/G1CP/Content/NinjaInit.d, src/Ninja/G1CP/Content/Tests/test031.d, src/Ninja/G1CP/Content_G1.src
Fixes #31. Wolf's dialog options regarding the mine crawler plates should disappear once the respective dialog was told.
Run automatic test with `test 31`.
=> #31: Remove Wolf's plate dialog

docs/changelog.md, src/Ninja/G1CP/Content/Fixes/Session/fix036_FiskFenceQuest.d, src/Ninja/G1CP/Content/NinjaInit.d, src/Ninja/G1CP/Content/Tests/test036.d, src/Ninja/G1CP/Content_G1.src
Fixes #36. The dialog is now available for two extra conditions
1. Mordrag is dead.
2. Mordrag stays at the new camp.
Run automatic test with `test 36`. The test executes the dialog condition function twice for both conditions mentioned above.
=> #36: Enable Fisk's fence quest

docs/changelog.md, src/Ninja/G1CP/Content/Fixes/Session/fix038_SnafDialogNek.d, src/Ninja/G1CP/Content/NinjaInit.d, src/Ninja/G1CP/Content/Tests/test038.d, src/Ninja/G1CP/Content_G1.src
Fixes #38. The Nek dialog is now properly available even if the recipe quest is closed.
Run automatic test with `test 38`.
Here too, the German translation of the changelog is still missing. @AmProsius can you complete that?
=> #38: Snaf now correctly offers the Nek dialog 

docs/changelog.md, src/Ninja/G1CP/Content/Fixes/Session/fix040_AlephKeyDialog.d, src/Ninja/G1CP/Content/NinjaInit.d, src/Ninja/G1CP/Content/Tests/test040.d, src/Ninja/G1CP/Content_G1.src
Fixes #40. The dialog option (after snitching on Aleph) now disappears,
Run automatic test with `test 40`.
=> #40: Aleph does not offer the keys again

docs/changelog.md, src/Ninja/G1CP/Content/Fixes/Session/fix043_EN_SkillMissingWhitespace.d, src/Ninja/G1CP/Content/NinjaInit.d, src/Ninja/G1CP/Content/Tests/test043.d, src/Ninja/G1CP/Content_G1.src
Fixes #43. The screen information about learning skills now contains proper whitespace. This fix is for English localization only and should be tested for English (unfixed), English (fixed) and for another localization, where the fix does not apply.
Run automatic test with `test 43`. The test will throw an error if the localization is not English, but will pass.
I only added the fix to the English section of the changelog.md.
=> #43: Fix whitespace of learning print (EN)

docs/changelog.md, src/Ninja/G1CP/Content/Fixes/Session/fix079_WolfDexDialog.d, src/Ninja/G1CP/Content/NinjaInit.d, src/Ninja/G1CP/Content/Tests/test079.d, src/Ninja/G1CP/Content_G1.src
Fixes #79. Wolf now trains the player dexterity if they are part of the New Camp, but no longer if the player is part of the Guard.
Run automatic test with `test 79`. The test can fail in two ways: If the dialog condition returns true, when the player is a guard, or if it returns false, when the player is part of the New Camp.
=> #79: Wolf's training dialog is now properly triggered

docs/changelog.md, src/Ninja/G1CP/Content/Fixes/Session/fix060_JesseQuest.d, src/Ninja/G1CP/Content/NinjaInit.d, src/Ninja/G1CP/Content/Tests/test060.d, src/Ninja/G1CP/Content_G1.src
Fixes #60. Jesse's quest can now be triggered.
Run automatic test with `test 60`.
The quest does not have a name and is also not tracked in the quest log. Therefore its (non-existing) name is not listed in the changelog.
=> #60: Fix Jesse's quest

docs/changelog.md, src/Ninja/G1CP/Content/Fixes/Session/fix012_RangedDoubleXP.d, src/Ninja/G1CP/Content/NinjaInit.d, src/Ninja/G1CP/Content/Tests/test012.d, src/Ninja/G1CP/Content_G1.src
Fixes #12. The player no longer receives double XP when killing an NPC in ranged combat.
Run manual test with `test 12`. This test only supplies a helpless NPC to work on.
=> #12: Prevent double XP for ranged combat

docs/changelog.md, src/Ninja/G1CP/Content/Fixes/Session/fix049_DungeonKeyText.d, src/Ninja/G1CP/Content/NinjaInit.d, src/Ninja/G1CP/Content/Tests/test049.d, src/Ninja/G1CP/Content_G1.src
Fixes #49. Interestingly, I found a way to fix this issue completely language independent. The exact wording does not matter: if the second line of text overwrites the first line, it will be corrected.
Run automatic test with `test 49`.
The test, however, only supports English and German localization. Both should be tested (I only tested English). Three additional tests are yet to be performed.
1. Test in German localization (especially important because of the umlaut 'ö' in the key text)
1. Do an additional _manual_ test where the key was in the world before the fix was applied, i.e. create a game save with the key inserted, then apply the fix, load the game and manually confirm that the key's text was updated.
1. Do a test on a mod that already fixed the issue.
=> #49: Fix the item text of the dungeon key

docs/changelog.md, src/Ninja/G1CP/Content/Fixes/Session/fix030_SilasTrade.d, src/Ninja/G1CP/Content/NinjaInit.d, src/Ninja/G1CP/Content/Tests/test030.d, src/Ninja/G1CP/Content_G1.src
Fixes #30. It turns out, this fix does not impact game saves (i.e. does not have to be reverted and reapplied). That made it much easier.
Run manual test with `test 30`. The test requires to check manually if Silas now offers to trade more than once.
=> #30: Silas now trades with the player more than once

docs/changelog.md, src/Ninja/G1CP/Content/Fixes/Session/fix021_FletcherClosedQuest.d, src/Ninja/G1CP/Content/Misc/topic.d, src/Ninja/G1CP/Content/NinjaInit.d, src/Ninja/G1CP/Content/Tests/test021.d, src/Ninja/G1CP/Content_G1.src
Fixes #21. Fletch now leaves the quest closed if it is already.
Run automatic test with `test 21`.
**Not ready for merge:** The German translation of the changelog is missing.
=> #21: Prevent Fletcher from reopening quest

docs/changelog.md, src/Ninja/G1CP/Content/Fixes/Session/fix039_FingersTeachDialog.d, src/Ninja/G1CP/Content/NinjaInit.d, src/Ninja/G1CP/Content/Tests/test039.d, src/Ninja/G1CP/Content_G1.src
Fixes #39. Fingers now teaches according to the players skill
Run manual test with `test 39`. This test is very tedious. The player is only teleported to Fingers and the dialog unlocked. To test, the user has to learn all the skills (use `insert ch` to get enough learning points) and check if the dialog choices appear according to the player's skill.
=> #39: Fix Fingers teaching dialog choices

docs/changelog.md, src/Ninja/G1CP/Content/Fixes/Session/fix078_HumanAttackOrc.d, src/Ninja/G1CP/Content/NinjaInit.d, src/Ninja/G1CP/Content/Tests/test078.d, src/Ninja/G1CP/Content_G1.src
Fixes #78. Human NPCs now recognize orcs as enemies. This should fix the quest in the orc grave yard.
Run manual test with `test 78`.
Additionally to the test suite, the fix should be check with Baal Lukor in the orc grave yard. I have not done that yet.
=> #78: Humans recognize orcs as enemies

docs/changelog.md, src/Ninja/G1CP/Content/Fixes/Session/fix042_GuardExitDialog.d, src/Ninja/G1CP/Content/NinjaInit.d, src/Ninja/G1CP/Content/Tests/test042.d, src/Ninja/G1CP/Content_G1.src
Fixes #42. The guards should now only have one exit dialog
Run manual test with `test 42`.
=> #42: Remove duplicate EXIT dialog from guards

docs/changelog.md, src/Ninja/G1CP/Content/Fixes/Session/fix027_DraxTeachingDialog.d, src/Ninja/G1CP/Content/NinjaInit.d, src/Ninja/G1CP/Content/Tests/test027.d, src/Ninja/G1CP/Content_G1.src
Fixes #27. The teaching dialog is no longer unlocked *and* the log entry is not created, before the player as provided a beer to Drax.
Run automatic test with `test 27`. Although the automatic test should cover everything, an additional manual confirmation may not hurt.
=> #27: Update conditions for Drax to teach

docs/changelog.md, src/Ninja/G1CP/Content/Fixes/Session/fix011_PassGuardsCombatMode.d, src/Ninja/G1CP/Content/NinjaInit.d, src/Ninja/G1CP/Content/Tests/test011.d, src/Ninja/G1CP/Content_G1.src
Fixes #11.
The fix [suggested here](../issues/11#issuecomment-757133978) is not really tackling this specific problem of reacting to a drawn weapon, but rather:
1. It disables the reaction for **all** NPCs (not just the guards!) if the player was just warned by a passage guard.
1. It disables the reaction for **any** NPC that has important infos (a dialog)
Here the issues that arise from the above:
1. If the player draws a weapon near any guarded gate, *no* NPC will react. As soon as the player walks a bit away from the gate, NPC would suddenly react. This is a very strange behavior.
2. I first thought this is a very important thing to address: NPCs with important infos should talk to the player even if the weapon is drawn. But it's actually a very bad change. This would trigger dialogs …
=> #11: Fix passage guard reaction for drawn weapon

docs/changelog.md, src/Ninja/G1CP/Content/Fixes/Session/fix102_JesseProtectionMoneyPay.d, src/Ninja/G1CP/Content/Fixes/Session/fix102_PayForJesse.d, src/Ninja/G1CP/Content/NinjaInit.d, src/Ninja/G1CP/Content/Tests/test102.d, src/Ninja/G1CP/Content_G1.src
Fixes #102. The player now loses 10 ore when paying for Jesse.
Run automatic test with `test 102`.
=> #102: Fix paying ore for Jesse

docs/changelog.md, src/Ninja/G1CP/Content/Fixes/Session/fix109_BloodwynProtectionMoneyPayLater.d, src/Ninja/G1CP/Content/Fixes/Session/fix109_BloodwynProtectionMoneySecond.d, src/Ninja/G1CP/Content/NinjaInit.d, src/Ninja/G1CP/Content/Tests/test109.d, src/Ninja/G1CP/Content_G1.src
Fixes #109. Paying Bloodwyn later costs ore.
Run automatic test with `test 109`.
=> #109: Pay Bloodwyn later

docs/changelog.md, src/Ninja/G1CP/Content/Fixes/Session/fix136_FollowLadder.d, src/Ninja/G1CP/Content/NinjaInit.d, src/Ninja/G1CP/Content/Tests/test136.d, src/Ninja/G1CP/Content_G1.src
NPCs don't use ladders properly when they are following the player.
NPCs now use ladders properly when they are following the player.
**Steps to reproduce the issue**
1. Enter the Free Mine with Gorn.
2. Let Gorn run off the main platform.
**Testing**
Run a manual test with `test 136`.
When Gorn runs off the platform, he struggles to come up again. He starts using the ladder, but falls down midways.
=> NPCs cannot use ladders when following the player

docs/changelog.md, src/Ninja/G1CP/Content/Fixes/Session/fix044_BugmeatCategory.d, src/Ninja/G1CP/Content/NinjaInit.d, src/Ninja/G1CP/Content/Tests/test044.d, src/Ninja/G1CP/Content_G1.src
Fixes #44. List bug meat as food.
Run automatic test with `test 44`. An additional manual check for the item might be nice. I already did that partially.
Insert code: `insert itat_meatbug_01`.
=> #44: List bug meat as food

docs/changelog.md, src/Ninja/G1CP/Content/Fixes/Session/fix125_ButcherText.d, src/Ninja/G1CP/Content/NinjaInit.d, src/Ninja/G1CP/Content/Tests/test125.d, src/Ninja/G1CP/Content_G1.src
Fixes #125. Correct the item text (description) of the butcher sword to one handed.
Run automatic test with `test 125`. This test only works for English and German localization. So far, I only tested it for English scripts.
=> #125: Fix item text of butcher sword

docs/changelog.md, src/Ninja/G1CP/Content/Fixes/Session/fix122_CavalornDailyRoutine.d, src/Ninja/G1CP/Content/NinjaInit.d, src/Ninja/G1CP/Content/Tests/test122.d, src/Ninja/G1CP/Content_G1.src
Fixes #122.
Run manual test with `test 122`. Consecutive calls of this test will alternate the time between day time and night time. This allows to check if Cavalorn's daily routine is fully corrected.
=> #122: Fix Cavalorn's daily routine

docs/changelog.md, src/Ninja/G1CP/Content/Fixes/Session/fix126_SharkyTrade.d, src/Ninja/G1CP/Content/NinjaInit.d, src/Ninja/G1CP/Content/Tests/test126.d, src/Ninja/G1CP/Content_G1.src
Fixes #126. Fix trade menu for Sharky.
Run manual test with `test 126`. The PC is teleported to Sharky and the dialog option is available for manual testing.
=> #126: Remove trade menu during Shark's quest dialog

docs/changelog.md, src/Ninja/G1CP/Content/Fixes/Session/fix157_SpeedPotion2Value.d, src/Ninja/G1CP/Content/NinjaInit.d, src/Ninja/G1CP/Content/Tests/test157.d, src/Ninja/G1CP/Content_G1.src
Fixes #157. The second speed potion (Potion of Velocity) has the correct ore value.
Run automatic test with `test 157`. This test will be important to check with mods that might have already fixed the issue.
This fix will only take effect when the Potion of Velocity has the *same* ore value as the Potion of Swiftness. This way, it is ensured that a mod did not deliberately changed the ore value.
=> #157: Fix the ore value of the second speed potion

docs/changelog.md, src/Ninja/G1CP/Content/Fixes/Session/fix158_SpeedPotion3Value.d, src/Ninja/G1CP/Content/NinjaInit.d, src/Ninja/G1CP/Content/Tests/test158.d, src/Ninja/G1CP/Content_G1.src
Fixes #158. The second speed potion (Potion of Haste) has the correct ore value.
Run automatic test with `test 158`. This test will be important to check with mods that might have already fixed the issue.
This fix will only take effect when the Potion of Haste has the *same* ore value as the Potion of Swiftness. This way it is ensured that a mod did not deliberately changed the ore value.
=> #158: Fix the ore value of the third speed potion

docs/changelog.md, src/Ninja/G1CP/Content/Fixes/Session/fix032_GornAttackFreeMine.d, src/Ninja/G1CP/Content/NinjaInit.d, src/Ninja/G1CP/Content/Tests/test032.d, src/Ninja/G1CP/Content_G1.src
Gorn sometimes attacks the player on the raid of the Free Mine.
Gorn no longer attacks the player on the raid of the Free Mine.
**Test**
Run manual test with `test 32`.
*Triggered by killing a guard when out of sight of Gorn.*
*Triggered by defeating guards of the Old Camp.*
*Triggered by Gorn seeing a guard of the Old Camp attacking the PC first.*
=> Gorn attacks the player in the Free Mine

docs/changelog.md, src/Ninja/G1CP/Content/Fixes/Session/fix175_EN_RiceLordKeyName.d, src/Ninja/G1CP/Content/Tests/test175.d, src/Ninja/G1CP/Content/patchInit.d, src/Ninja/G1CP/Content_G1.src
In the English localization there's a typo in the Rice Lord's Key's name.
**Changelog**
Changed the name "Rice Lord's Bowl" to "Rice Lord's Key".
Looks like the translator made a mistake by translating *Schüssel* (Bowl) instead of *Schlüssel* (Key).
=> Spelling - Rice Lord's Key (EN)

docs/changelog.md, src/Ninja/G1CP/Content/Fixes/Gamesave/fix093_DE_HoratioLogEntry.d, src/Ninja/G1CP/Content/Fixes/gamesave.d, src/Ninja/G1CP/Content/Tests/test093.d, src/Ninja/G1CP/Content_G1.src
In the German localization there is a typo for a log entry concerning Horatio's offer.
**Changelog**
Im Tagebucheintrag zu der Quest "Horatio der Bauer" die Phrase "[...] stärker zuzuschalgen." korrigiert zu "[...] stärker zuzuschlagen."
=> Spelling - Horatio: "zuzuschlagen" (DE)

CHANGELOG.md, src/Ninja/G1CP/Content/Fixes/Session/fix144_DE_GomezArmorName.d, src/Ninja/G1CP/Content/Tests/test144.d, src/Ninja/G1CP/Content/patchInit.d, src/Ninja/G1CP/Content_G1.src
In the German localization there's a typo in Gomez' Armor's name.
**Changelog**
Den Namen "Gomez'Rüstung" korrigiert zu "Gomez' Rüstung".
=> Spelling - Gomez' Armor (DE)

CHANGELOG.md, docs/changelog_de.md, src/Ninja/G1CP/Content/Fixes/Session/fix149_DE_EN_ImprovedOreArmorName.d, src/Ninja/G1CP/Content/Tests/test149.d, src/Ninja/G1CP/Content/patchInit.d, src/Ninja/G1CP/Content_G1.src
In the German and English localization there's a typo in the Improved Ore Armor's name.
**Changelog**
* Den Namen "verbesserte Erzrüstung" korrigiert zu "Verbesserte Erzrüstung".
* Changed the name "Improved ore Armor" to "Improved Ore Armor".
=> Spelling - Improved Ore Armor (DE/EN)

docs/changelog_de.md, src/Ninja/G1CP/Content/Fixes/Session/fix091_DE_HoratioAddChoiceAvenge.d, src/Ninja/G1CP/Content/Tests/test091.d, src/Ninja/G1CP/Content/patchInit.d, src/Ninja/G1CP/Content_G1.src
In the German localization, the "Reislord" is wrongly referenced to as "Ricelord". Also the written dialog line differs from the spoken dialog.
**Changelog**
Dialogzeile mit Horatio: "Ja. Ich will es mit Ricelord und seinen Schlägern aufnehmen können!" korrigiert zu "Ja. Ich will es mit dem Reislord und seinen Schlägern aufnehmen können!"
Reference:
https://github.com/AmProsius/gothic-1-community-patch/blob/f0c8d15ce2879c7913146364f5fdc9899a534639/scriptbase/_work/Data/Scripts/Content/Story/Missions/DIA_BAU_901_Horatio.d#L319-L322
Original:
```d
if	Npc_KnowsInfo(hero,DIA_Jeremiah_Horatio)
{
Info_AddChoice	 (DIA_Horatio_ThoughtSTR, "Ja. Ich will es mit Ricelord und seinen Schlägern aufnehmen können!",DIA_Horatio_ThoughtSTR_Ricelord);
};
``` …
=> Spelling - Horatio: "Ricelord" (DE)

docs/changelog.md, src/Ninja/G1CP/Content/Fixes/Gamesave/fix121_DE_LogTopicShrikeHut.d, src/Ninja/G1CP/Content/Fixes/gamesave.d, src/Ninja/G1CP/Content/Tests/test121.d, src/Ninja/G1CP/Content_G1.src
In the German localization of the game, there's a typo in the quest name of "Shrike's Hut".
No typo in the quest name.
**Changelog**
Die Quest "Shrike's Hütte" korrigiert zu "Shrikes Hütte".
In Germany this is called a *[Deppenapostroph](https://de.wikipedia.org/wiki/Apostroph#Diskussion_%C3%BCber_fehlerhafte_Verwendung)*.
=> Spelling - Quest: "Shrikes Hütte" (DE)

src/Ninja/G1CP/Content/Fixes/Session/fix147_DE_CrawlerPlateArmorName.d, src/Ninja/G1CP/Content/Tests/test147.d
In the German localization there's a typo in the Crawler Plate Armor's name.
**Changelog**
Den Namen "Crawler-Plattenrüstung" korrigiert zu "Crawlerplatten-Rüstung".
https://github.com/AmProsius/gothic-1-community-patch/blob/703d7554a7623acd2abbf79318c53dd3ed744690/scriptbase/_work/Data/Scripts/Content/Items/Armor.d#L1057
=> Spelling - Crawler Plate Armor (DE)

docs/changelog_de.md, src/Ninja/G1CP/Content/Fixes/Session/fix148_DE_AncientOreArmorName.d, src/Ninja/G1CP/Content/Tests/test148.d, src/Ninja/G1CP/Content/patchInit.d, src/Ninja/G1CP/Content_G1.src
In the German localization there's a typo in the Ancient Ore Armor's name.
**Changelog**
Den Namen "antike Erzrüstung" korrigiert zu "Antike Erzrüstung".
=> Spelling - Ancient Ore Armor (DE)

docs/changelog_de.md, src/Ninja/G1CP/Content/Fixes/Session/fix200_DE_ImprovedOreArmorDescription.d, src/Ninja/G1CP/Content/Fixes/Session/fix200_DE_ImprovedOreArmorText.d, src/Ninja/G1CP/Content/Tests/test200.d, src/Ninja/G1CP/Content/patchInit.d, src/Ninja/G1CP/Content_G1.src
In the German localization the text of the Improved Ore Armor is too long and doesn't fit in the text box.
**Changelog**
Die Beschreibung der Verbesserten Erzrüstung passt jetzt in die Textbox.
=> Text of Improved Ore Armor too long (DE)

docs/changelog_de.md, src/Ninja/G1CP/Content/Fixes/Session/fix201_DE_AncientOreArmorDescription.d, src/Ninja/G1CP/Content/Fixes/Session/fix201_DE_AncientOreArmorText.d, src/Ninja/G1CP/Content/Tests/test201.d, src/Ninja/G1CP/Content/patchInit.d, src/Ninja/G1CP/Content_G1.src
In the German localization the text of the Ancient Ore Armor is too long and doesn't fit in the text box.
Die Beschreibung der Antiken Erzrüstung passt jetzt in die Textbox und enthält keinen Rechtschreibfehler mehr.
=> Text of Ancient Ore Armor too long (DE)

docs/changelog_de.md, src/Ninja/G1CP/Content/Fixes/Session/fix145_DE_LightMercenarysArmorName.d, src/Ninja/G1CP/Content/Tests/test145.d, src/Ninja/G1CP/Content/patchInit.d, src/Ninja/G1CP/Content_G1.src
In the German localization there's a typo in the Light Mercenary Armor's name.
**Changelog**
Den Namen "leichte Söldnerrüstung" korrigiert zu "Leichte Söldnerrüstung".
=> Spelling - Light Mercenary's Armor (DE)

docs/changelog_de.md, src/Ninja/G1CP/Content/Fixes/Session/fix146_DE_NovicesLoinclothName.d, src/Ninja/G1CP/Content/Tests/test146.d, src/Ninja/G1CP/Content/patchInit.d, src/Ninja/G1CP/Content_G1.src
In the German localization there's a typo in the Novice's Loincloth's name.
**Changelog**
Den Namen "Novizen Rock" korrigiert zu "Novizenrock".
=> Spelling - Novice's Loincloth (DE)

docs/changelog_de.md, src/Ninja/G1CP/Content/Fixes/Session/fix172_DE_KalomsRecipeName.d, src/Ninja/G1CP/Content/Tests/test172.d, src/Ninja/G1CP/Content/patchInit.d, src/Ninja/G1CP/Content_G1.src
In the German localization there's a typo in Kalom's Recipe's name.
**Changelog**
Den Namen "Kalom's Rezept" korrigiert zu "Kaloms Rezept".
=> Spelling - Kalom's Recipe (DE)

docs/changelog_de.md, src/Ninja/G1CP/Content/Fixes/Session/fix173_DE_GomezKeyText.d, src/Ninja/G1CP/Content/Tests/test173.d, src/Ninja/G1CP/Content/patchInit.d, src/Ninja/G1CP/Content_G1.src
In the German localization there's a typo in Gomez' Key's text.
**Changelog**
Im Text von Gomez' Schlüssel die Phrase "Öffnet Gomez Truhen" korrigiert zu "Öffnet Gomez' Truhen".
=> Spelling - Gomez' Key: "Gomez' Truhen" (DE)

CHANGELOG.md, docs/changelog_de.md, src/Ninja/G1CP/Content/Fixes/Gamesave/fix052_UseWithItemNCGrindstone.d, src/Ninja/G1CP/Content/Fixes/gamesave.d, src/Ninja/G1CP/Content/Tests/test052.d, src/Ninja/G1CP/Content_G1.src
The grindstone in the New Camp can be used without having a sword blade in the inventory.
The grindstone in the New Camp now correctly requires a sword blade to use.
It's currently possible to produce *Grobe Schwerter* without having Swordblades in the inventory.  
This issue was split into two further issues #212 #213.  
Add `useWithItem` with `ItMiSwordblade` to grindstone at `NC_HUT03_OUT_MOVEMENT`.
**Screenhots**
=> Exploit: Grindstone in the New Camp can be used without sword blade

docs/changelog_de.md, src/Ninja/G1CP/Content/Fixes/Session/fix142_TemplarVIPDialog.d, src/Ninja/G1CP/Content/Tests/test142.d, src/Ninja/G1CP/Content/patchInit.d, src/Ninja/G1CP/Content_G1.src
In the German localization a dialog line with an ambient templar is interchanged.
**Changelog**
Vertauschte Dialogzeilen mit einem Ambient-Templer korrigiert.
See #197 for pt. 2.
=> Dialog lines with ambient templar interchanged pt. 1

CHANGELOG.md, docs/changelog_de.md, src/Ninja/G1CP/Content/Fixes/Session/fix036_FiskFenceQuest.d, src/Ninja/G1CP/Content/Tests/test036.d
This PR constraints the conditions introduced in v1.1.0 in #36. Now the fence quest is only available if Mordrag was knocked down (default) or if he is dead. The additional option of him being in the New Camp was removed here.
Additionally, the fix was reimplemented to fix a major bug of overwriting the global variable `MordragKO_HauAb`, which would cause inwanted side-effects in other dialogs/story.
Fixes #36.
Run automatic test with `test 36`.
=> Improve fisk fence quest

CHANGELOG.md, docs/changelog_de.md, src/Ninja/G1CP/Content/Fixes/Session/fix004_NpcMoveNpcDefeated.d, src/Ninja/G1CP/Content/Tests/test004.d, src/Ninja/G1CP/Content/patchInit.d, src/Ninja/G1CP/Content_G1.src
NPCs confront the player when he is standing in their way even if he has defeated them before.
NPCs no longer confront the player when he is standing in their way if he has defeated them before.
=> NPCs are rude to the player even after defeating them

CHANGELOG.md, docs/changelog_de.md, src/Ninja/G1CP/Content/Fixes/Session/fix023_BaalNamibSellArmor.d, src/Ninja/G1CP/Content/Tests/test023.d, src/Ninja/G1CP/Content/patchInit.d, src/Ninja/G1CP/Content_G1.src
Baal Namib doesn't sell the Novice's Armor until chapter 3, but the player can already become a Templar in chapter 2.
Baal Namib now sells the Novice's Armor in chapter 2 already, if the Minecrawler Queen quest is running or completed.
=> Baal Namib sells Novice's Armor too late

CHANGELOG.md, docs/changelog_de.md, src/Ninja/G1CP/Content/Fixes/Session/fix181_SwineyGiveArmor.d, src/Ninja/G1CP/Content/Tests/test181.d, src/Ninja/G1CP/Content/patchInit.d, src/Ninja/G1CP/Content_G1.src
When Swiney gives a Digger's Dress to the player, he gives him his own equipped Digger's Dress.
Swiney no longer loses his own Digger's Dress when he gives one to the player.
=> Swiney gives his own pants to the player

CHANGELOG.md, docs/changelog_de.md, src/Ninja/G1CP/Content/Fixes/Session/fix182_GuardDialogDusty.d, src/Ninja/G1CP/Content/Tests/test182.d, src/Ninja/G1CP/Content/patchInit.d, src/Ninja/G1CP/Content_G1.src
When bringing Dusty to the Swamp Camp, the player can indefinitely bribe the gate guard to get EXP.
The gate guard can only be bribed once when bringing Dusty to the Swamp Camp.
**Steps to reproduce the issue**
1. Bribe the gate guard with Dusty following you.
2. Save the game
3. Load the save.
4. Bribe the gate guard again (if you have enough ore).
=> Exploit: The gate guard can be bribed multiple times with Dusty as a follower

CHANGELOG.md, docs/changelog_de.md, src/Ninja/G1CP/Content/Fixes/Session/fix214_GrahamDailyRoutine.d, src/Ninja/G1CP/Content/Tests/test214.d, src/Ninja/G1CP/Content/patchInit.d, src/Ninja/G1CP/Content_G1.src
Graham is supposed to sit at the campfire in the evening, but a typo in the waypoint name prevents him from doing so.
Graham now correctly sits at the campfire in the evening.
Bug and fix provided by [NikX94](https://github.com/AmProsius/gothic-1-community-patch/issues/211#issuecomment-808914450).
=> Graham doesn't sit at campfire

docs/changelog_de.md, src/Ninja/G1CP/Content/Fixes/Session/fix092_DE_HoratioAddChoiceWipeOut.d, src/Ninja/G1CP/Content/Tests/test092.d, src/Ninja/G1CP/Content/patchInit.d, src/Ninja/G1CP/Content_G1.src
In the German localization there is a noun marker missing. Also the written dialog line differs from the spoken dialog.
**Changelog**
Dialogoption mit Horatio: "Damit ich Reislord und seine Schläger fertigmachen kann!" korrigiert zu "Damit ich den Reislord und seine Schläger fertig machen kann!"
```d
func void DIA_Horatio_PleaseTeachSTR_Ricelord()
{
AI_Output (other, self,"DIA_Horatio_PleaseTeachSTR_Ricelord_15_00"); //Damit ich den Reislord und seine Schläger fertig machen kann!
AI_Output (self, other,"DIA_Horatio_PleaseTeachSTR_Ricelord_09_01"); //Hmm ... Du bist nicht der Erste, der das versucht.
horatio_StrFree = TRUE;
Info_ClearChoices(DIA_Horatio_PleaseTeachSTR );
};
```
=> Spelling - Horatio: "den Reislord" (DE)

CHANGELOG.md, src/Ninja/G1CP/Content/Fixes/Session/fix152_EN_ProtectionOfFireDescription.d, src/Ninja/G1CP/Content/Tests/test152.d, src/Ninja/G1CP/Content/patchInit.d, src/Ninja/G1CP/Content_G1.src
In the English localization the description of the ring *Protection of Fire* is inconsistent and grammatically incorrect.
**Changelog**
Changed description of ring "Protection of Fire" to "Ring of Fire Protection"
=> Spelling - Ring of Fire Protection (EN)

CHANGELOG.md, docs/changelog_de.md, src/Ninja/G1CP/Content/Fixes/Session/fix183_CorristoSellsRobe.d, src/Ninja/G1CP/Content/Tests/test183.d, src/Ninja/G1CP/Content/patchInit.d, src/Ninja/G1CP/Content_G1.src
The player can obtain more than one High Robe of Fire from Corristo.
Corristo now sells only one High Robe of Fire to the player.
**Steps to reproduce the issue**
1. Buy High Robe of Fire from Corristo.
2. Save the game.
3. Load the save.
4. Buy another High Robe of Fire from Corristo.
=> Corristo sells High Robe multiple times

CHANGELOG.md, docs/changelog_de.md, src/Ninja/G1CP/Content/Fixes/Session/fix215_GuyDailyRoutine.d, src/Ninja/G1CP/Content/Tests/test215.d, src/Ninja/G1CP/Content/patchInit.d, src/Ninja/G1CP/Content_G1.src
Guy is supposed to sit at the arena in the evening, but a typo in the waypoint name prevents him from doing so.
Guy now correctly sits at the arena in the evening.
Bug and fix provided by [NikX94](https://github.com/AmProsius/gothic-1-community-patch/issues/211#issuecomment-808921199).
=> Guy doesn't sit at arena

CHANGELOG.md, docs/changelog_de.md, src/Ninja/G1CP/Content/Fixes/Session/fix216_DiggerDailyRoutine.d, src/Ninja/G1CP/Content/Tests/test216.d, src/Ninja/G1CP/Content/patchInit.d, src/Ninja/G1CP/Content_G1.src
A Digger is supposed to repair his hut during daytime, but a typo in the waypoint name prevents him from doing so.
A Digger now correctly repairs his hut during daytime.
Bug and fix provided by [NikX94](https://github.com/AmProsius/gothic-1-community-patch/issues/211#issuecomment-808926648).
=> Digger doesn't repair hut

CHANGELOG.md, docs/changelog_de.md, src/Ninja/G1CP/Content/Fixes/Session/fix014_PortalCancelFight.d, src/Ninja/G1CP/Content/Tests/test014.d, src/Ninja/G1CP/Content/patchInit.d, src/Ninja/G1CP/Content_G1.src
The player can run into a room and immediately leave it to cancel a fight if the NPC has full HP.
The player can no longer cancel fights by entering and leaving a room.
=> The player can cancel fights by entering a room 

CHANGELOG.md, docs/changelog_de.md, src/Ninja/G1CP/Content/Fixes/Session/fix115_KillSittingDuck.d, src/Ninja/G1CP/Content/Tests/test115.d, src/Ninja/G1CP/Content/patchInit.d, src/Ninja/G1CP/Content_G1.src
When the player is fast enough, he can kill the orcs near the dummy Templars before the orcs kill the Templars. Then the dummy Templars just stand there doing nothing.
The dummy Templars in the orc graveyard are now already dead when the player enters the graveyard.
My suggestion would be to kill the dummy Templars when the player first enters the orc graveyard.
**Screenshot**
=> Dummy Templars survive in orc graveyard

CHANGELOG.md, docs/changelog_de.md, src/Ninja/G1CP/Content/Fixes/Gamesave/fix193_GateSwitchesStuck.d, src/Ninja/G1CP/Content/Fixes/gamesave.d, src/Ninja/G1CP/Content/Tests/test193.d, src/Ninja/G1CP/Content_G1.src
After using a switch/lever/winch to close a gate, the switch does not work anymore after loading a game and the gate is stuck.
Objects activated by switches/levers/winches are no longer stuck after loading a game.
**Steps to reproduce the issue**
1. Close a gate by using the respective switch.
2. Save the game.
3. Load the game.
4. The switch state returns to 0 while the gate remains in its triggered state: The gate will be stuck for good.
[Attached](https://www.sendspace.com/file/49pe45) the fix done by szapp 2 years ago.  
See also the original post on WoG: https://forum.worldofplayers.de/forum/threads/?p=25954985
=> Gates triggered by switches are stuck after loading

CHANGELOG.md, docs/changelog_de.md, src/Ninja/G1CP/Content/Fixes/Session/fix110_MobInteractCamera.d, src/Ninja/G1CP/Content/Tests/test110.d, src/Ninja/G1CP/Content/patchInit.d, src/Ninja/G1CP/Content_G1.src
When the player is sitting on a bench, the camera zooms too much into the player.
When the player is sitting on a bench, the camera no longer zooms too much into the player.
=> Weird camera distance when sitting on a bench

CHANGELOG.md, docs/changelog_de.md, src/Ninja/G1CP/Content/Fixes/Session/fix217_MercenaryDailyRoutine.d, src/Ninja/G1CP/Content/Tests/test217.d, src/Ninja/G1CP/Content/patchInit.d, src/Ninja/G1CP/Content_G1.src
A Mercenary is supposed to guard the palisade during the afternoon, but a typo in the waypoint name prevents him from doing so.
A Mercenary now correctly guards the palisade during the afternoon.
Bug and fix provided by [NikX94](https://github.com/AmProsius/gothic-1-community-patch/issues/211#issuecomment-808929770).
=> Mercenary doesn't guard the palisade

CHANGELOG.md, docs/changelog_de.md, src/Ninja/G1CP/Content/Fixes/Gamesave/fix045_SpawnSnappersMonastery.d, src/Ninja/G1CP/Content/Fixes/gamesave.d, src/Ninja/G1CP/Content/Misc/npc.d, src/Ninja/G1CP/Content/Tests/test045.d, src/Ninja/G1CP/Content_G1.src
Snappers don't spawn outside the Monastery ruins.
This fix corrects the spawn of the two snappers such that they appear in the game. On saving, this fix is reverted to leave no changes in the savegame. That means, the spawn of the snappers is invalidated again. However, if the player is currently in spawn range of the snappers when saving, their spawn is not reverted and they will be written to the savegame. In that event, they remain in the game. This is necessary to avoid inconsistencies when saving the game while engaging with the snappers.
=> Snappers don't spawn outside the Monastery ruins 

CHANGELOG.md, docs/changelog_de.md, src/Ninja/G1CP/Content/Fixes/Gamesave/fix203_LogEntryGrahamMerchant.d, src/Ninja/G1CP/Content/Fixes/gamesave.d, src/Ninja/G1CP/Content/Tests/test203.d, src/Ninja/G1CP/Content_G1.src
Graham is not listed in "Diary/General Info/Merchant in the Old Camp" if the topic wasn't previously created.
Graham is now listed in "Merchant in the Old Camp" in the journal.
Similar to #37.
=> Graham not listed as merchant

CHANGELOG.md, docs/changelog_de.md, src/Ninja/G1CP/Content/Fixes/Gamesave/fix205_LogEntryWolfMerchant.d, src/Ninja/G1CP/Content/Fixes/gamesave.d, src/Ninja/G1CP/Content/Tests/test205.d, src/Ninja/G1CP/Content_G1.src
Wolf is not listed in "Diary/General Info/Merchant in the New Camp" if the topic wasn't previously created.
Wolf is now listed in "Merchant in the New Camp" in the journal.
Similar to #37, #203 and #204.
=> Wolf not listed as merchant

CHANGELOG.md, docs/changelog_de.md, src/Ninja/G1CP/Content/Fixes/Session/fix176_InvItemTextValue.d, src/Ninja/G1CP/Content/Tests/test176.d, src/Ninja/G1CP/Content/patchInit.d, src/Ninja/G1CP/Content_G1.src
There are items that have no value. In the inventory it shows "Value:" but not number.
Items with no value no longer show an empty "Value:" in the inventory text.
The items have a value of 0 and therefor the value isn't displayed.
The bug has been reported in #177 #178 #179 #180.
=> The text of items with no value is incomplete in the inventory

CHANGELOG.md, docs/changelog_de.md, src/Ninja/G1CP/Content/Fixes/Gamesave/fix226_PotionStonehengeChest.d, src/Ninja/G1CP/Content/Fixes/gamesave.d, src/Ninja/G1CP/Content/Tests/test226.d, src/Ninja/G1CP/Content_G1.src, src/Ninja/G1CP/Testsuite.src
Due to a typo, there's a mana potion missing in one of the chests in the crypt under the stonehenge.
A mana potion is now correctly inserted in one of the chests in the crypt under the stonehenge.
Bug and fix provided by [N1kX94](https://github.com/AmProsius/gothic-1-community-patch/issues/211#issuecomment-808912236).
```
[% oCMobContainer:oCMobInter:oCMOB:zCVob 64513 16024]
pack=int:0
presetName=string:
bbox3DWS=rawFloat:-35454.0898 2280.677 -15369.6855 -35365.7734 2357.57202 -15269.3906
trafoOSToWSRot=raw:ceb5a63e00000000a40c723f000000000000803f00000000a40c72bf00000000ceb5a63e
trafoOSToWSPos=vec3:-35412.4219 2280.677 -15320.7129
vobName=string:CHEST
visual=string:CHESTBIG_OCCHESTMEDIUMLOCKED.MDS
showVisual=bool:1 …
```
=> Missing mana potion in stonehenge crypt chest

docs/changelog_de.md, src/Ninja/G1CP/Content/Fixes/Session/fix236_DE_OrcDogGuild.d, src/Ninja/G1CP/Content/Tests/test236.d, src/Ninja/G1CP/Content/patchInit.d, src/Ninja/G1CP/Content_G1.src, src/Ninja/G1CP/Testsuite.src
In the German localization of the game there' a typo in the guild name of the monster "Orc Dog".
**Changelog**
Der Name in der Gildenzuordnung des Monsters "Ork-Hund" heißt nun korrekt "Orkhund".
=> Spelling - Guild: "Orkhund" (DE)

CHANGELOG.md, docs/changelog_de.md, src/Ninja/G1CP/Content/Fixes/Session/fix220_GorNaRanDialogMad.d, src/Ninja/G1CP/Content/Tests/test220.d, src/Ninja/G1CP/Content/patchInit.d, src/Ninja/G1CP/Content_G1.src, src/Ninja/G1CP/Testsuite.src
Gor Na Ran attacks the player character in chapter 6. Considering the corresponding dialog, it seems that he is supposed to be in the Sleeper's temple.
Gor Na Ran no longer attacks the player character in chapter 6.
Bug provided by [Blubbler](https://forum.worldofplayers.de/forum/threads/1574630-Release-Gothic-1-Community-Patch/page2?p=26716794&viewfull=1#post26716794).
https://github.com/AmProsius/gothic-1-community-patch/blob/7406330aae51b13622443869aea1c7140d5dc99d/scriptbase/_work/Data/Scripts/Content/Story/Missions/DIA_TPL_1405_GorNaRan.d#L61-L168
=> Gor Na Ran attacks the player character in chapter 6

CHANGELOG.md, docs/changelog_de.md, src/Ninja/G1CP/Content/Fixes/Session/fix228_LaresDialogFindGorn.d, src/Ninja/G1CP/Content/Tests/test228.d, src/Ninja/G1CP/Content/patchInit.d, src/Ninja/G1CP/Content_G1.src, src/Ninja/G1CP/Testsuite.src
Because of an incorrect assignment, Gorn can't be asked about in ambient dialogs after Lares talks of his existence.
Gorn can now correctly be asked about in ambient dialogs after the player talked to Lares.
Bug and fix provided by [N1kX94](https://github.com/AmProsius/gothic-1-community-patch/issues/211#issuecomment-809048931).
=> Gorn can't be asked about after talking to Lares

docs/changelog_de.md, src/Ninja/G1CP/Content/Fixes/Session/fix232_DE_TransformBloodflyDescription.d, src/Ninja/G1CP/Content/Tests/test043.d, src/Ninja/G1CP/Content/Tests/test125.d, src/Ninja/G1CP/Content/Tests/test144.d, src/Ninja/G1CP/Content/Tests/test145.d, src/Ninja/G1CP/Content/Tests/test146.d, src/Ninja/G1CP/Content/Tests/test147.d, src/Ninja/G1CP/Content/Tests/test148.d, src/Ninja/G1CP/Content/Tests/test149.d, src/Ninja/G1CP/Content/Tests/test152.d, src/Ninja/G1CP/Content/Tests/test172.d, src/Ninja/G1CP/Content/Tests/test173.d, src/Ninja/G1CP/Content/Tests/test174.d, src/Ninja/G1CP/Content/Tests/test175.d, src/Ninja/G1CP/Content/Tests/test200.d, src/Ninja/G1CP/Content/Tests/test201.d, src/Ninja/G1CP/Content/Tests/test232.d, src/Ninja/G1CP/Content/Tests/test235.d, src/Ninja/G1CP/Content/Tests/test236.d, src/Ninja/G1CP/Content/Testsuite/inspect.d, src/Ninja/G1CP/Content/patchInit.d, src/Ninja/G1CP/Content_G1.src, src/Ninja/G1CP/Testsuite.src
In the German localization of the game there' a typo in the description of the scroll "Transform into Bloodfly".
**Changelog**
Die Spruchrolle "Verwandlung Bloodfly" heißt nun korrekt "Verwandlung Blutfliege".
Bug provided by [Blubbler](https://forum.worldofplayers.de/forum/threads/1574630-Release-Gothic-1-Community-Patch/page2?p=26716794&viewfull=1#post26716794).
=> Spelling - Transform Bloodfly (DE)

docs/changelog_de.md, src/Ninja/G1CP/Content/Fixes/Session/fix231_DE_TransformOrcDogDescription.d, src/Ninja/G1CP/Content/Tests/test231.d, src/Ninja/G1CP/Content/patchInit.d, src/Ninja/G1CP/Content_G1.src, src/Ninja/G1CP/Testsuite.src
In the German localization of the game there' a typo in the description of the scroll "Transform into Orc Dog".
**Changelog**
Die Spruchrolle "Verwandlung Orcdog" heißt nun korrekt "Verwandlung Orkhund".
Bug provided by [Blubbler](https://forum.worldofplayers.de/forum/threads/1574630-Release-Gothic-1-Community-Patch/page2?p=26716794&viewfull=1#post26716794).
=> Spelling - Transform Orc Dog (DE)

CHANGELOG.md, docs/changelog_de.md, src/Ninja/G1CP/Content/Fixes/Session/fix225_MordragNcGetOut.d, src/Ninja/G1CP/Content/Tests/test225.d, src/Ninja/G1CP/Content/patchInit.d, src/Ninja/G1CP/Content_G1.src, src/Ninja/G1CP/Testsuite.src
Mordrag can be told to "get out of here" even if he guided the player to the New Camp.
Mordrag can no longer be told to "get out of here" if he guided the player to the New Camp.
Bug provided by [Blubbler](https://forum.worldofplayers.de/forum/threads/1574630-Release-Gothic-1-Community-Patch/page2?p=26716794&viewfull=1#post26716794).
Reference for the proposed fix:
https://github.com/AmProsius/gothic-1-community-patch/blob/e66b303623c042ec5cfc387a1b0d4bd352605f12/scriptbase/_work/Data/Scripts/Content/Story/Missions/DIA_ORG_826_Mordrag.d#L328-L334
=> Mordrag can be told to "get out" in New Camp

CHANGELOG.md, docs/changelog_de.md, src/Ninja/G1CP/Content/Fixes/Session/fix191_CordOneHanded.d, src/Ninja/G1CP/Content/Tests/test191.d, src/Ninja/G1CP/Content/patchInit.d, src/Ninja/G1CP/Content_G1.src, src/Ninja/G1CP/Testsuite.src
Cord's dialog option to teach One-handed Sword Level 2 appears before the player learned Level 1.
Cord's dialog option to teach One-handed Sword Level 2 now appears only after the player learned Level 1.
* The German translation for *One-handed Sword Level 2* is *Einhänder Stufe 2*.
* The player can't actually learn Level 2 before Level 1, but for consistency reasons I suggest to hide the dialog option (see #39). Therefore the issue is marked as `opinionated`.
https://github.com/AmProsius/gothic-1-community-patch/blob/746a440f78e80e8a1e3195de6768b0427687ef77/scriptbase/_work/Data/Scripts/Content/Story/Missions/DIA_TPL_1402_GorNaToth.d#L441-L449
https://github.com/AmProsius/gothic-1-community-patch/blob/746a440f78e80e8a1e3195 …
=> Cord teaches One-handed Sword Level 2 too soon

CHANGELOG.md, docs/changelog_de.md, src/Ninja/G1CP/Content/Fixes/Gamesave/fix127_LockedChestNc.d, src/Ninja/G1CP/Content/Fixes/gamesave.d, src/Ninja/G1CP/Content/Tests/test127.d, src/Ninja/G1CP/Content_G1.src, src/Ninja/G1CP/Testsuite.src
Right next to the house of Buster there is a chest that cannot be opened/picked.
The closed chest next to Buster's house can now be picked.
```
[% oCMobContainer:oCMobInter:oCMOB:zCVob 64513 6384]
pack=int:0
presetName=string:OC_CHEST_MEDIUM_NC
bbox3DWS=rawFloat:-55190.5391 2919.41309 1100.78479 -55120.3203 2996.30811 1188.93396
trafoOSToWSRot=raw:2bd58e3d0000000068607f3f000000000000803f0000000068607fbf000000002bd58e3d
trafoOSToWSPos=vec3:-55158.1367 2919.41309 1144.36926
vobName=string:OC_CHEST_MEDIUM
visual=string:CHESTBIG_OCCHESTMEDIUMLOCKED.MDS
showVisual=bool:1
visualCamAlign=enum:0
cdStatic=bool:0
cdDyn=bool:1
staticVob=bool:1
dynShadow=enum:0
[visual zCModel 0 6385]
[]
[ai % 0 0]
[]
focusName=string:Chest …
```
=> One chest in NC cannot be opened
