src/Ninja/G1CP/Content/Fixes/Session/fix019_ScorpioFightDialog.d, src/Ninja/G1CP/Content/NinjaInit.d, src/Ninja/G1CP/Content/Tests/test019.d, src/Ninja/G1CP/Content_G1.src
This PR is very similar to the previous dialog condition changes.
Run an automated test (no manual confirmation) with `test 19`.
=> #19: Add condition to Scorpio's fight dialog

src/Ninja/G1CP/Content/Fixes/Session/fix020_KirgoGivesBeer.d, src/Ninja/G1CP/Content/NinjaInit.d, src/Ninja/G1CP/Content/Tests/test020.d, src/Ninja/G1CP/Content_G1.src
This fix is straight forward.
Run a test with `test 20`.
Closes #20.
=> #20: Correct who is giving who a beer

src/Ninja/G1CP/Content/Fixes/Session/fix022_YBerionAttacks.d, src/Ninja/G1CP/Content/NinjaInit.d, src/Ninja/G1CP/Content/Tests/test022.d, src/Ninja/G1CP/Content_G1.src
The test for this issue only works when in chapter one.
Run it with `test 22`.
Closes #22.
=> #22: Y'Berion now attacks the player

src/Ninja/G1CP/Content/Fixes/Session/fix025_SaturasSellsRobe.d, src/Ninja/G1CP/Content/NinjaInit.d, src/Ninja/G1CP/Content/Tests/test025.d, src/Ninja/G1CP/Content_G1.src
This fix is straight forward.
It can be verified with `test 25`.
Closes #25.
=> #25: Saturas no longer sells the robe twice

src/Ninja/G1CP/Content/Fixes/Session/fix026_LaresGuardAttacks.d, src/Ninja/G1CP/Content/NinjaInit.d, src/Ninja/G1CP/Content/Tests/test026.d, src/Ninja/G1CP/Content_G1.src
Run a test with `test 26`.
Closes #26
=> #26: Lares's guard now attacks

src/Ninja/G1CP/Content/Fixes/Session/fix028_MordragNoEscort.d, src/Ninja/G1CP/Content/NinjaInit.d, src/Ninja/G1CP/Content/Tests/test028.d, src/Ninja/G1CP/Content_G1.src
The test is simple. 
Run `test 28`.
Closes #28.
=> #28: Mordrag now refuses to escort player

src/Ninja/G1CP/Content/Fixes/Session/fix029_BusterAcrobatics.d, src/Ninja/G1CP/Content/NinjaInit.d, src/Ninja/G1CP/Content/Tests/test029.d, src/Ninja/G1CP/Content_G1.src
Another automatic test with `test 29`.
Closes #29.
=> #29: Make Buster only teach Acrobatics once 

docs/changelog.md, src/Ninja/G1CP/Content/Fixes/Session/fix112_JackalProtectionMoneyPay.d, src/Ninja/G1CP/Content/Fixes/Session/fix112_JackalProtectionMoneyPayLater.d, src/Ninja/G1CP/Content/NinjaInit.d, src/Ninja/G1CP/Content/Tests/test112.d, src/Ninja/G1CP/Content_G1.src
Fixes #112. Pay Jackal protection money later.
Run automatic test with `test 112`.
=> #112: Pay Jackal later

docs/changelog.md, src/Ninja/G1CP/Content/Fixes/Session/fix111_JackalProtectionMoneyPay.d, src/Ninja/G1CP/Content/NinjaInit.d, src/Ninja/G1CP/Content/Tests/test111.d, src/Ninja/G1CP/Content_G1.src
Fixes #111. Pay protection money to Jackal.
Run automatic test with `test 111`.
=> #111: Pay Jackal

docs/changelog.md, src/Ninja/G1CP/Content/Fixes/Gamesave/fix124_GateGuardID.d, src/Ninja/G1CP/Content/Fixes/gamesave.d, src/Ninja/G1CP/Content/Tests/test124.d, src/Ninja/G1CP/Content_G1.src
Fixes #124. The daily routine of the guard is fixed. Nevertheless, the original problem is not. See [here](../issues/124#issuecomment-787094949). For the time being I will leave this PR as a draft until we address the underlying issue. If we do, it should be solved in a separate fix. This fix here is complete.
Run manual test with `test 124`. The test will break the game and it will not be possible to continue playing. Save the game beforehand.
=> #124: Exchange castle gate guard ID

CHANGELOG.md, docs/changelog_de.md, src/Ninja/G1CP/Content/Fixes/Gamesave/fix037_LogEntryGravoMerchant.d, src/Ninja/G1CP/Content/Fixes/gamesave.d, src/Ninja/G1CP/Content/Tests/test037.d, src/Ninja/G1CP/Content_G1.src
Gravo isn't listed in "Diary/General info/Merchant in the Old Camp" if the topic wasn't previously created.
=> Gravo not listed as merchant 

CHANGELOG.md, docs/changelog_de.md, src/Ninja/G1CP/Content/Fixes/Gamesave/fix051_StonehengeCryptChest.d, src/Ninja/G1CP/Content/Fixes/gamesave.d, src/Ninja/G1CP/Content/Tests/test051.d, src/Ninja/G1CP/Content_G1.src
**Description**
There is a chest in the crypt that's behind a wall.
Moved chest in the crypt from outside to inside the focus room to make it available to the player.
=> Chest in stonehenge crypt behind wall 

docs/changelog_de.md, src/Ninja/G1CP/Content/Fixes/Gamesave/fix133_DE_LogEntryScatty.d, src/Ninja/G1CP/Content/Fixes/gamesave.d, src/Ninja/G1CP/Content/Tests/test133.d, src/Ninja/G1CP/Content/patchInit.d, src/Ninja/G1CP/Content_G1.src
In the German localization there's a typo for a log entry concerning the defeat versus Kirgo.
**Changelog**
Im Tagebucheintrag nach dem Kampf gegen Kirgo die Phrase "Meinem Niederlage gegen Kirgo [...]" korrigiert zu "Meine Niederlage gegen Kirgo [...]".
=> Spelling - Scatty: "Meine" (DE)

CHANGELOG.md, docs/changelog_de.md, src/Ninja/G1CP/Content/Fixes/Session/fix129_DrakeBodySkin.d, src/Ninja/G1CP/Content/Tests/test129.d, src/Ninja/G1CP/Content/patchInit.d, src/Ninja/G1CP/Content_G1.src, src/Ninja/G1CP/Testsuite.src
Drake's body skin color does not match his head.
Drake's body skin color now matches his head.
Instance `Grd_260_Drake`.
=> Drake has wrong body skin color

CHANGELOG.md, docs/changelog_de.md, src/Ninja/G1CP/Content/Fixes/Session/fix168_GorNaBarBecomeTemplar.d, src/Ninja/G1CP/Content/Tests/test168.d, src/Ninja/G1CP/Content/patchInit.d, src/Ninja/G1CP/Content_G1.src, src/Ninja/G1CP/Testsuite.src
No matter the player's guild, Gor Na Bar tells him to speak to Cor Angar about becoming a templar and a log entry is created. 
Gor Na Bar now tells only novices to speak to Cor Angar about becoming a templar.
=> Gor Na Bar offers to become a templar to anyone

src/Ninja/G1CP/Content/Fixes/Session/fix233_DE_OrcDogName.d, src/Ninja/G1CP/Content/Misc/npc.d
Refactor the fix where an NPC is renamed.
=> Refactor rename NPC fix

src/Ninja/G1CP/Content/Fixes/Session/fix030_SilasTrade.d, src/Ninja/G1CP/Content/Fixes/Session/fix126_SharkyTrade.d, src/Ninja/G1CP/Content/Misc/info.d
Refactor the fixes where an info instance int variable is changed.
=> Refactor info int variable fixes

src/Ninja/G1CP/Content/Fixes/Session/fix124_GateGuardId.d, src/Ninja/G1CP/Content/Misc/npc.d
Refactor the fix where an NPC instance int variable is changed.
=> Refactor NPC int variable fix

src/Ninja/G1CP/Content/Fixes/Session/fix043_EN_SkillMissingWhitespace.d, src/Ninja/G1CP/Content/Symbols/string.d
=> Refactor replace string constant fix

src/Ninja/G1CP/Content/Fixes/Session/fix102_JesseProtectionMoneyPay.d, src/Ninja/G1CP/Content/Fixes/Session/fix109_BloodwynProtectionMoneyPayLater.d, src/Ninja/G1CP/Content/Fixes/Session/fix111_JackalProtectionMoneyPay.d, src/Ninja/G1CP/Content/Fixes/Session/fix112_JackalProtectionMoneyPayLater.d, src/Ninja/G1CP/Content/Misc/item.d, src/Ninja/G1CP/Content_G1.src
Refactor fixes where an item transaction is added to a dialog.
=> Refactor add item transaction to dialog fixes

src/Ninja/G1CP/Content/Bytecode/string.d, src/Ninja/G1CP/Content/Fixes/Session/fix0149_DE_EN_ImprovedOreArmorName.d, src/Ninja/G1CP/Content/Fixes/Session/fix0233_DE_OrcDogName.d, src/Ninja/G1CP/Content/Misc/npc.d, src/Ninja/G1CP/Content/Symbols/string.d, src/Ninja/G1CP/Content/Templates/npc.d, src/Ninja/G1CP/Content/Tests/test0235.d, src/Ninja/G1CP/Content/Tests/test0236.d, src/Ninja/G1CP/Content_G1.src, templates/renameNpc/session.d, templates/renameNpc/test.d
=> Add template for rename NPC instance
